apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-exporter
  namespace: kube-system
  labels:
    k8s-app: events-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: events-exporter
  template:
    metadata:
      labels:
        k8s-app: events-exporter
    spec:
      serviceAccountName: events-exporter
      containers:
      - name: events-exporter
        image: simonswine/events-exporter:0.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-exporter
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: events-exporter
rules:
- apiGroups: [""]
  resources:
  - events
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: events-exporter
subjects:
- kind: ServiceAccount
  name: events-exporter
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: events-exporter
  apiGroup: rbac.authorization.k8s.io
